"""
Type stubs for diskcache_rs package

This package provides a high-performance disk cache implementation in Rust
with Python bindings, compatible with python-diskcache API.
"""

import io
from contextlib import contextmanager
from pathlib import Path
from typing import (
    Any,
    Callable,
    Dict,
    Iterator,
    List,
    Optional,
    Set,
    Tuple,
    Type,
    Union,
)

# Version
__version__: str

# ---------------------------------------------------------------------------
# Constants (from diskcache.core)
# ---------------------------------------------------------------------------

class _Constant(tuple):
    def __new__(cls, name: str) -> "_Constant": ...
    def __repr__(self) -> str: ...

ENOVAL: _Constant
"""Sentinel for cache miss."""

UNKNOWN: _Constant
"""Sentinel for unknown values."""

DEFAULT_SETTINGS: Dict[str, Any]
"""Default cache settings dictionary."""

EVICTION_POLICY: Dict[str, Dict[str, Optional[str]]]
"""Eviction policy definitions."""

# ---------------------------------------------------------------------------
# Exceptions and Warnings
# ---------------------------------------------------------------------------

class Timeout(Exception):
    """Database timeout expired."""
    ...

class EmptyDirWarning(UserWarning):
    """Warning for empty directories found during check."""
    ...

class UnknownFileWarning(UserWarning):
    """Warning for unknown files found during check."""
    ...

# Main Cache Classes
class Cache:
    """High-performance disk cache compatible with python-diskcache API"""

    def __init__(
        self,
        directory: Optional[Union[str, Path]] = None,
        timeout: float = 60.0,
        disk_min_file_size: int = 32768,
        **kwargs: Any,
    ) -> None: ...
    def __contains__(self, key: Any) -> bool: ...
    def __enter__(self) -> Cache: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __reversed__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __del__(self) -> None: ...
    def __getstate__(self) -> Tuple[str, float]: ...
    def __setstate__(self, state: Tuple[str, float]) -> None: ...
    def get(
        self,
        key: Any,
        default: Any = None,
        read: bool = False,
        expire_time: bool = False,
        tag: bool = False,
        retry: bool = False,
    ) -> Any: ...
    def set(
        self,
        key: Any,
        value: Any,
        expire: Optional[float] = None,
        read: bool = False,
        tag: Optional[str] = None,
        retry: bool = False,
    ) -> bool: ...
    def add(
        self,
        key: Any,
        value: Any,
        expire: Optional[float] = None,
        read: bool = False,
        tag: Optional[str] = None,
        retry: bool = False,
    ) -> bool: ...
    def delete(self, key: Any, retry: bool = False) -> bool: ...
    def pop(
        self,
        key: Any,
        default: Any = None,
        expire_time: bool = False,
        tag: bool = False,
        retry: bool = False,
    ) -> Any: ...
    def clear(self, retry: bool = False) -> int: ...
    def close(self) -> None: ...
    def exists(self, key: Any) -> bool: ...
    def keys(self) -> List[Any]: ...
    def values(self) -> List[Any]: ...
    def items(self) -> List[Tuple[Any, Any]]: ...
    def iterkeys(self, reverse: bool = False) -> Iterator[Any]: ...
    def expire(self, now: Optional[float] = None, retry: bool = False) -> int: ...
    def evict(self, tag: str, retry: bool = False) -> int: ...
    def cull(self, retry: bool = False) -> int: ...
    def check(self, fix: bool = False, retry: bool = False) -> List[str]: ...
    def create_tag_index(self) -> None: ...
    def drop_tag_index(self) -> None: ...
    def stats(self, enable: bool = True, reset: bool = False) -> Dict[str, Any]: ...
    def volume(self) -> int: ...
    def reset(self, key: str, value: Any = None, update: bool = True) -> Any: ...
    def read(self, key: Any, retry: bool = False) -> io.BytesIO: ...
    def touch(
        self, key: Any, expire: Optional[float] = None, retry: bool = False
    ) -> bool: ...
    def incr(
        self,
        key: Any,
        delta: Union[int, float] = 1,
        default: Union[int, float] = 0,
        retry: bool = False,
    ) -> Union[int, float]: ...
    def decr(
        self,
        key: Any,
        delta: Union[int, float] = 1,
        default: Union[int, float] = 0,
        retry: bool = False,
    ) -> Union[int, float]: ...
    def push(
        self,
        value: Any,
        prefix: Optional[str] = None,
        side: str = "back",
        expire: Optional[float] = None,
        read: bool = False,
        tag: Optional[str] = None,
        retry: bool = False,
    ) -> Any: ...
    def pull(
        self,
        prefix: Optional[str] = None,
        default: Tuple = ...,
        side: str = "front",
        expire_time: bool = False,
        tag: bool = False,
        retry: bool = False,
    ) -> Any: ...
    def peek(
        self,
        prefix: Optional[str] = None,
        default: Tuple = ...,
        side: str = "front",
        expire_time: bool = False,
        tag: bool = False,
        retry: bool = False,
    ) -> Any: ...
    def peekitem(
        self,
        last: bool = True,
        expire_time: bool = False,
        tag: bool = False,
        retry: bool = False,
    ) -> Tuple: ...
    def vacuum(self) -> None: ...
    def memoize(
        self,
        name: Optional[str] = None,
        typed: bool = False,
        expire: Optional[float] = None,
        tag: Optional[str] = None,
        ignore: Set[str] = ...,
    ) -> Callable: ...
    def transact(self, retry: bool = False) -> Any: ...

    # Properties
    @property
    def directory(self) -> Path: ...
    @property
    def timeout(self) -> float: ...
    @property
    def disk(self) -> Any: ...

class FanoutCache:
    """Fanout cache implementation for better concurrency"""

    def __init__(
        self,
        directory: Optional[Union[str, Path]] = None,
        shards: int = 8,
        timeout: float = 60.0,
        **kwargs: Any,
    ) -> None: ...
    def __contains__(self, key: Any) -> bool: ...
    def __enter__(self) -> FanoutCache: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __reversed__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __del__(self) -> None: ...
    def __getstate__(self) -> Tuple[str, int, float]: ...
    def __setstate__(self, state: Tuple[str, int, float]) -> None: ...
    def get(
        self,
        key: Any,
        default: Any = None,
        read: bool = False,
        expire_time: bool = False,
        tag: bool = False,
        retry: bool = False,
    ) -> Any: ...
    def set(
        self,
        key: Any,
        value: Any,
        expire: Optional[float] = None,
        read: bool = False,
        tag: Optional[str] = None,
        retry: bool = False,
    ) -> bool: ...
    def add(
        self,
        key: Any,
        value: Any,
        expire: Optional[float] = None,
        read: bool = False,
        tag: Optional[str] = None,
        retry: bool = False,
    ) -> bool: ...
    def delete(self, key: Any, retry: bool = False) -> bool: ...
    def pop(
        self,
        key: Any,
        default: Any = None,
        expire_time: bool = False,
        tag: bool = False,
        retry: bool = False,
    ) -> Any: ...
    def clear(self, retry: bool = False) -> int: ...
    def close(self) -> None: ...
    def exists(self, key: Any) -> bool: ...
    def keys(self) -> List[Any]: ...
    def values(self) -> List[Any]: ...
    def items(self) -> List[Tuple[Any, Any]]: ...
    def iterkeys(self, reverse: bool = False) -> Iterator[Any]: ...
    def expire(self, now: Optional[float] = None, retry: bool = False) -> int: ...
    def evict(self, tag: str, retry: bool = False) -> int: ...
    def cull(self, retry: bool = False) -> int: ...
    def check(self, fix: bool = False, retry: bool = False) -> List[str]: ...
    def create_tag_index(self) -> None: ...
    def drop_tag_index(self) -> None: ...
    def stats(self, enable: bool = True, reset: bool = False) -> Dict[str, Any]: ...
    def volume(self) -> int: ...
    def reset(self, key: str, value: Any = None) -> Any: ...
    def read(self, key: Any, retry: bool = False) -> io.BytesIO: ...
    def touch(
        self, key: Any, expire: Optional[float] = None, retry: bool = False
    ) -> bool: ...
    def incr(
        self,
        key: Any,
        delta: Union[int, float] = 1,
        default: Union[int, float] = 0,
        retry: bool = False,
    ) -> Union[int, float]: ...
    def decr(
        self,
        key: Any,
        delta: Union[int, float] = 1,
        default: Union[int, float] = 0,
        retry: bool = False,
    ) -> Union[int, float]: ...
    def push(
        self,
        value: Any,
        prefix: Optional[str] = None,
        side: str = "back",
        expire: Optional[float] = None,
        read: bool = False,
        tag: Optional[str] = None,
        retry: bool = False,
    ) -> Any: ...
    def pull(
        self,
        prefix: Optional[str] = None,
        default: Tuple = ...,
        side: str = "front",
        expire_time: bool = False,
        tag: bool = False,
        retry: bool = False,
    ) -> Any: ...
    def peek(
        self,
        prefix: Optional[str] = None,
        default: Tuple = ...,
        side: str = "front",
        expire_time: bool = False,
        tag: bool = False,
        retry: bool = False,
    ) -> Any: ...
    def peekitem(
        self,
        last: bool = True,
        expire_time: bool = False,
        tag: bool = False,
        retry: bool = False,
    ) -> Tuple: ...
    def vacuum(self) -> None: ...
    def memoize(
        self,
        name: Optional[str] = None,
        typed: bool = False,
        expire: Optional[float] = None,
        tag: Optional[str] = None,
        ignore: Set[str] = ...,
    ) -> Callable: ...
    def transact(self, retry: bool = False) -> Any: ...
    def cache(
        self, name: str, timeout: Optional[float] = None, **kwargs: Any
    ) -> Cache: ...
    def deque(self, name: str, maxlen: Optional[int] = None) -> "Deque": ...
    def index(self, name: str) -> "Index": ...

    # Properties
    @property
    def directory(self) -> Path: ...
    @property
    def timeout(self) -> float: ...
    @property
    def disk(self) -> Any: ...

class Deque:
    """Persistent double-ended queue based on Cache"""

    def __init__(
        self,
        iterable: Any = (),
        directory: Optional[Union[str, Path]] = None,
        maxlen: Optional[int] = None,
    ) -> None: ...
    def append(self, value: Any) -> None: ...
    def appendleft(self, value: Any) -> None: ...
    def pop(self) -> Any: ...
    def popleft(self) -> Any: ...
    def peek(self) -> Any: ...
    def peekleft(self) -> Any: ...
    def clear(self) -> None: ...
    def extend(self, iterable: Any) -> None: ...
    def extendleft(self, iterable: Any) -> None: ...
    def close(self) -> None: ...
    def copy(self) -> "Deque": ...
    def count(self, value: Any) -> int: ...
    def remove(self, value: Any) -> None: ...
    def reverse(self) -> None: ...
    def rotate(self, steps: int = 1) -> None: ...
    def transact(self) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __reversed__(self) -> Iterator[Any]: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, value: Any) -> bool: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def __iadd__(self, other: Any) -> "Deque": ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __enter__(self) -> "Deque": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __getstate__(self) -> Tuple: ...
    def __setstate__(self, state: Tuple) -> None: ...
    @property
    def maxlen(self) -> Optional[int]: ...
    @property
    def directory(self) -> Path: ...

class Index:
    """Persistent ordered mapping based on Cache"""

    def __init__(
        self,
        *args: Any,
        directory: Optional[Union[str, Path]] = None,
        **kwargs: Any,
    ) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __reversed__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __enter__(self) -> "Index": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __getstate__(self) -> Tuple: ...
    def __setstate__(self, state: Tuple) -> None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def pop(self, key: str, default: Any = None) -> Any: ...
    def popitem(self, last: bool = True) -> Tuple[str, Any]: ...
    def setdefault(self, key: str, default: Any = None) -> Any: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[Any]: ...
    def items(self) -> List[Tuple[str, Any]]: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def clear(self) -> None: ...
    def peekitem(self, last: bool = True) -> Tuple[str, Any]: ...
    def close(self) -> None: ...
    def transact(self) -> Any: ...
    def memoize(
        self,
        name: Optional[str] = None,
        typed: bool = False,
        ignore: Set[str] = ...,
    ) -> Callable: ...
    def push(
        self,
        value: Any,
        prefix: Optional[str] = None,
        side: str = "back",
    ) -> Any: ...
    def pull(
        self,
        prefix: Optional[str] = None,
        default: Tuple = ...,
        side: str = "front",
    ) -> Any: ...
    @property
    def cache(self) -> Cache: ...
    @property
    def directory(self) -> Path: ...

# Fast Cache Classes
class FastCache(Cache):
    """Ultra-fast cache implementation with optimized storage backends"""

    pass

class FastFanoutCache(FanoutCache):
    """Ultra-fast fanout cache implementation"""

    pass

# Pickle Cache
class PickleCache:
    """High-performance pickle cache with expiration support"""

    def __init__(self, cache_dir: Union[str, Path] = "pickle_cache") -> None: ...
    def cache_object(self, key: str, obj: Any, expire_hours: float = 24.0) -> None: ...
    def get_cached_object(self, key: str) -> Optional[Any]: ...
    def clear_cache(self) -> None: ...
    def is_expired(self, key: str) -> bool: ...
    def delete_object(self, key: str) -> bool: ...
    def list_cached_objects(self) -> List[str]: ...
    def get_cache_stats(self) -> Dict[str, Any]: ...

# Utility Functions
def cache_object(
    key: str,
    obj: Any,
    expire_hours: float = 24.0,
    cache_dir: Union[str, Path] = "pickle_cache",
) -> None:
    """Cache an object with expiration"""
    ...

def get_cached_object(
    key: str, cache_dir: Union[str, Path] = "pickle_cache"
) -> Optional[Any]:
    """Retrieve a cached object"""
    ...

def clear_cache(cache_dir: Union[str, Path] = "pickle_cache") -> None:
    """Clear all cached objects"""
    ...

# Rust Functions (from _diskcache_rs module)
def rust_pickle_dumps(obj: Any) -> Any:
    """High-performance pickle serialization using Rust"""
    ...

def rust_pickle_loads(data: Any) -> Any:
    """High-performance pickle deserialization using Rust"""
    ...

# ---------------------------------------------------------------------------
# Disk Serialization Classes
# ---------------------------------------------------------------------------

class Disk:
    """Cache key and value serialization for SQLite database and filesystem."""

    def __init__(
        self,
        directory: Union[str, Path],
        min_file_size: int = 0,
        pickle_protocol: int = ...,
    ) -> None: ...
    @property
    def directory(self) -> Path: ...
    def hash(self, key: Any) -> int: ...
    def put(self, key: Any) -> Tuple[bytes, bool]: ...
    def get(self, key: Any, raw: bool) -> Any: ...
    def store(
        self, value: Any, read: bool = False, key: Any = ...
    ) -> Tuple[int, int, Optional[str], Any]: ...
    def fetch(
        self, mode: int, filename: str, value: Any, read: bool = False
    ) -> Any: ...
    def filename(
        self, key: Any = ..., value: Any = ...
    ) -> Tuple[str, str]: ...
    def remove(self, filename: str) -> None: ...

class JSONDisk(Disk):
    """Cache key and value serialization using JSON with optional compression."""

    def __init__(
        self,
        directory: Union[str, Path],
        compress_level: int = 1,
        **kwargs: Any,
    ) -> None: ...

# ---------------------------------------------------------------------------
# Recipes: Synchronization Primitives
# ---------------------------------------------------------------------------

class Lock:
    """Cross-process and cross-thread lock backed by Cache."""

    def __init__(
        self,
        cache: Cache,
        key: Any,
        expire: Optional[float] = None,
        tag: Optional[str] = None,
    ) -> None: ...
    def acquire(self) -> None: ...
    def release(self) -> None: ...
    def locked(self) -> bool: ...
    def __enter__(self) -> "Lock": ...
    def __exit__(self, *exc_info: Any) -> None: ...

class RLock:
    """Cross-process and cross-thread re-entrant lock backed by Cache."""

    def __init__(
        self,
        cache: Cache,
        key: Any,
        expire: Optional[float] = None,
        tag: Optional[str] = None,
    ) -> None: ...
    def acquire(self) -> None: ...
    def release(self) -> None: ...
    def __enter__(self) -> "RLock": ...
    def __exit__(self, *exc_info: Any) -> None: ...

class BoundedSemaphore:
    """Cross-process and cross-thread bounded semaphore backed by Cache."""

    def __init__(
        self,
        cache: Cache,
        key: Any,
        value: int = 1,
        expire: Optional[float] = None,
        tag: Optional[str] = None,
    ) -> None: ...
    def acquire(self) -> None: ...
    def release(self) -> None: ...
    def __enter__(self) -> "BoundedSemaphore": ...
    def __exit__(self, *exc_info: Any) -> None: ...

class Averager:
    """Recipe for calculating a running average backed by Cache."""

    def __init__(
        self,
        cache: Cache,
        key: Any,
        expire: Optional[float] = None,
        tag: Optional[str] = None,
    ) -> None: ...
    def add(self, value: float) -> None: ...
    def get(self) -> Optional[float]: ...
    def pop(self) -> Optional[float]: ...

# ---------------------------------------------------------------------------
# Recipes: Decorators
# ---------------------------------------------------------------------------

def throttle(
    cache: Cache,
    count: int,
    seconds: float,
    name: Optional[str] = None,
    expire: Optional[float] = None,
    tag: Optional[str] = None,
    time_func: Callable[[], float] = ...,
    sleep_func: Callable[[float], None] = ...,
) -> Callable: ...

def barrier(
    cache: Cache,
    lock_factory: Type[Union[Lock, RLock, BoundedSemaphore]],
    name: Optional[str] = None,
    expire: Optional[float] = None,
    tag: Optional[str] = None,
) -> Callable: ...

def memoize_stampede(
    cache: Cache,
    expire: float,
    name: Optional[str] = None,
    typed: bool = False,
    tag: Optional[str] = None,
    beta: float = 1,
    ignore: tuple = (),
) -> Callable: ...

# ---------------------------------------------------------------------------
# Utility Functions from Recipes
# ---------------------------------------------------------------------------

def full_name(func: Callable) -> str:
    """Return full module-qualified name of *func*."""
    ...

def args_to_key(
    base: tuple,
    args: tuple,
    kwargs: dict,
    typed: bool,
    ignore: tuple = (),
) -> tuple:
    """Create cache key from function arguments."""
    ...

# Backward compatibility
DiskCache = Cache

# All exports
__all__ = [
    # Core cache classes
    "Cache",
    "FanoutCache",
    "Deque",
    "Index",
    # Constants
    "DEFAULT_SETTINGS",
    "ENOVAL",
    "EVICTION_POLICY",
    "UNKNOWN",
    # Disk serialization
    "Disk",
    "JSONDisk",
    # Exceptions and warnings
    "Timeout",
    "EmptyDirWarning",
    "UnknownFileWarning",
    # Recipes: synchronization primitives
    "Lock",
    "RLock",
    "BoundedSemaphore",
    "Averager",
    # Recipes: decorators
    "barrier",
    "memoize_stampede",
    "throttle",
    # diskcache_rs extras
    "FastCache",
    "FastFanoutCache",
    "PickleCache",
    "cache_object",
    "get_cached_object",
    "clear_cache",
    "rust_pickle_dumps",
    "rust_pickle_loads",
    "DiskCache",
]
