# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

def detect_diskcache_format_py(path:builtins.str) -> builtins.bool:
    r"""
    Python wrapper for detect_diskcache_format
    """

def rust_pickle_dumps(obj:typing.Any) -> typing.Any:
    r"""
    High-performance pickle serialization using Rust
    """

def rust_pickle_loads(data:typing.Any) -> typing.Any:
    r"""
    High-performance pickle deserialization using Rust
    """

